spring.application.name=assignment-service
server.port=8084

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=c##assignment_schema
spring.datasource.password=assignment123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT Secret Key
app.jwt-secret=VGhpc0lzTXlTZWNyZXRLZXlGb3JKV1RUb2tlbjEyMzQ1Njc4OTA=