spring.application.name=api-gateway

server.port=8080

app.jwt-secret=VGhpc0lzTXlTZWNyZXRLZXlGb3JKV1RUb2tlbjEyMzQ1Njc4OTA=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.routes[0].uri=lb://HSMS-AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# USER SERVICE - CUSTOMERS
spring.cloud.gateway.routes[1].id=USER-CUSTOMERS
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# USER SERVICE - TECHNICIANS
spring.cloud.gateway.routes[2].id=USER-TECHNICIANS
spring.cloud.gateway.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/technicians/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# BOOKING SERVICE
spring.cloud.gateway.routes[3].id=BOOKING-SERVICE
spring.cloud.gateway.routes[3].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/service-requests/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

# CATALOG SERVICE
spring.cloud.gateway.routes[4].id=CATALOG-SERVICE
spring.cloud.gateway.routes[4].uri=lb://CATALOG-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/categories/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

# ASSIGNMENT SERVICE
spring.cloud.gateway.routes[5].id=ASSIGNMENT-SERVICE
spring.cloud.gateway.routes[5].uri=lb://ASSIGNMENT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/assignments/**
spring.cloud.gateway.routes[5].filters[0]=AuthenticationFilter
#spring.cloud.gateway.routes[5].filters[1]=RewritePath=/api/assignments/(?<segment>.*), /assignments/$\{segment}

# EXECUTION SERVICE
spring.cloud.gateway.routes[6].id=EXECUTION-SERVICE
spring.cloud.gateway.routes[6].uri=lb://EXECUTION-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/records/**
spring.cloud.gateway.routes[6].filters[0]=AuthenticationFilter

# FEEDBACK SERVICE
spring.cloud.gateway.routes[7].id=FEEDBACK-SERVICE
spring.cloud.gateway.routes[7].uri=lb://FEEDBACK-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/feedback/**
spring.cloud.gateway.routes[7].filters[0]=AuthenticationFilter

# PAYMENT SERVICE
spring.cloud.gateway.routes[8].id=PAYMENT-SERVICE
spring.cloud.gateway.routes[8].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[8].filters[0]=AuthenticationFilter

# ANALYTICS SERVICE
spring.cloud.gateway.routes[9].id=ANALYTICS-SERVICE
spring.cloud.gateway.routes[9].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/analytics/**
spring.cloud.gateway.routes[9].filters[0]=AuthenticationFilter

# NOTIFICATION SERVICE
spring.cloud.gateway.routes[10].id=NOTIFICATION-SERVICE
spring.cloud.gateway.routes[10].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[10].filters[0]=AuthenticationFilter
