spring.application.name=hsms-auth-service

server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##auth_schema
spring.datasource.password=auth123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.jwt-secret=VGhpc0lzTXlTZWNyZXRLZXlGb3JKV1RUb2tlbjEyMzQ1Njc4OTA=
app.jwt-expiration-milliseconds=86400000

spring.cloud.config.import-check.enabled=false


management.endpoints.web.exposure.include=*